- name: Application git clone
  git: 
    repo: https://github.com/shaileshsutar88/deploy.git
    dest: /var/www/html

- name: "restart services"
  service: >
    name= "{{ item }}"
    state=restarted
  with_items:
    - nginx
    - php7.0-fpm