- name: "Install Nginx"
  apt: >
    pkg=nginx
    state=latest
    update_cache=yes
    cache_valid_time=3600

- name: "Install MySQL server"
  apt: >
    pkg=mysql-server
    state=latest
    update_cache=yes
    cache_valid_time=3600

- name: "Install php-fpm"
  apt: >
    pkg={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - php-fpm
    - php-mysql
