- name: "Installing Base Packages"
  apt: >
    pkg={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=3600
  with_items:
  - vim
  - htop
  - dnsutils
  - ansible
  - tree
  - curl
  - screen
  - traceroute
  - unattended-upgrades
  - sysstat

- name: "Edit config file"
  command: "{{ item }}"
  with_items:
    - sudo sed -i 's:AutoFixInterruptedDpkg "False";:AutoFixInterruptedDpkg "True";:g' /etc/apt/apt.conf.d/50unattended-upgrades
    - sudo sed -i 's:Remove-Unused-Dependencies "False";:Remove-Unused-Dependencies "True";:g' /etc/apt/apt.conf.d/50unattended-upgrades